name: Main CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  # ═══════════════════════════════════════════════
  # ÉTAPE 1 : BUILD & TESTS
  # ═══════════════════════════════════════════════
  build-and-test:
    uses: ./.github/workflows/build-unit-tests.yml

  # ═══════════════════════════════════════════════
  # ÉTAPE 2 : ANALYSE DE SÉCURITÉ STATIQUE (SAST)
  # ═══════════════════════════════════════════════
  code-quality-sast:
    needs: build-and-test
    uses: ./.github/workflows/code-quality-sast.yml

  # ═══════════════════════════════════════════════
  # ÉTAPE 3 : DÉTECTION DE SECRETS
  # ═══════════════════════════════════════════════
  secret-scanning:
    needs: build-and-test
    uses: ./.github/workflows/secret-scanning.yml

  # ═══════════════════════════════════════════════
  # ÉTAPE 4 : ANALYSE DES DÉPENDANCES (SCA)
  # ═══════════════════════════════════════════════
  sca-dependency-scan:
    needs: build-and-test
    uses: ./.github/workflows/sca-dependency-scan.yml
    secrets: inherit

  # ═══════════════════════════════════════════════
  # ÉTAPE 5 : SÉCURITÉ INFRASTRUCTURE AS CODE
  # ═══════════════════════════════════════════════
  secure-iac-dockerfile-scan:
    needs: build-and-test
    uses: ./.github/workflows/secure-iac-dockerfile-scan.yml

  # ═══════════════════════════════════════════════
  # ÉTAPE 6 : BUILD & SCAN DOCKER
  # ═══════════════════════════════════════════════
  build-and-scan-docker:
    needs: [code-quality-sast, secret-scanning, secure-iac-dockerfile-scan]
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit

  # ═══════════════════════════════════════════════
  # ÉTAPE 7 : PUBLICATION DOCKER HUB
  # ═══════════════════════════════════════════════
  publish-docker-hub:
    needs: [build-and-scan-docker]
    uses: ./.github/workflows/publish-docker-hub.yml
    secrets: inherit

  # ═══════════════════════════════════════════════
  # ÉTAPE 8 : TESTS DAST
  # ═══════════════════════════════════════════════
  dast-zap-test:
    needs: publish-docker-hub
    uses: ./.github/workflows/dast-zap-test.yml
    secrets: inherit

  # ═══════════════════════════════════════════════
  # ÉTAPE 9 : DÉPLOIEMENT
  # ═══════════════════════════════════════════════
  deploy-docker:
    needs: dast-zap-test
    uses: ./.github/workflows/deploy-production-server.yml
    secrets: inherit
